# -*- coding: utf-8 -*-
"""eliminador_cuentas_sin_movimiento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwg5wNmmabXPbsXWlrnqeTdYjBnk9zD4
"""

import pandas as pd
import numpy as np



#esta funcion recibe un dataframe en pandas necesariamente de 7 columnas
#las columnas que debemos revisar son de la 4 a la 7 (3 a 6 en python)
#si la primer columna del renglon es vacia se elimina
#si las columnas mencionadas son TODAS vacias o NaN se elimina el renglon
#la funcion regresa la tabla modificada


def ProcesarExcel(tabla):

  primerIndice = np.argmax(tabla.iloc[:, 0]== "baan")
  tabla = tabla.iloc[primerIndice:].copy()


  #convierte las columnas a numerico
  for indice in range(3, 7):
      tabla.iloc[1:, indice] = pd.to_numeric(tabla.iloc[1:, indice] )
      tabla.iloc[1:, indice] = np.round(tabla.iloc[1:, indice], 3)

  #almacenamos los indices de los renglonesdescartados
  indicesDescartados = []

  renglonesVacios = 0 #contamos los renglones vacios
  renglonesSinMovimientos = 0 #contamos las cuentas sin movimientos

  #recorremos cada renglon del dataframe con un ciclo for
  #len(tabla ) nos da el numero de renglones del dataframe
  for renglon in range(len(tabla)):
    #si la primera entrada del renglon es vacio o nulo, ese renglon se elimina
    if pd.isna(tabla.iloc[renglon, 0]):
      indicesDescartados.append(tabla.index[renglon]) # Append original index
      renglonesVacios += 1

    else: #en otro caso

      #hay que revisar si todas las columnas de 3 a 6 (Python indices 2 to 5) son vacias o NaN
      #de ser el caso hay que eliminar el renglon

      # Select the relevant columns for the condition
      columnasChecar = tabla.iloc[renglon, 3:7]

      # Check if all values in columns 2 to 5 are either 0 or NaN
      condicion1 = ( (columnasChecar == 0) | (pd.isna(columnasChecar)) ).all()


      #revisamos las condiciones
      if condicion1 :
        indicesDescartados.append(tabla.index[renglon]) # Append original index
        renglonesSinMovimientos += 1


  #para eliminar seleccionamos inplace para que lo haga dentro de la tabla
  #y axis =0 porque queremos eleminar el indice especificado en renglon
  tabla.drop(indicesDescartados, inplace= True ,axis=0)


  tabla.to_csv("tablaProcesada.csv")

  #regresamos la tabla en pandas
  return tabla